project_id = "takvthfatlcjsqgssnta"

[functions.send-contact-form]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = false

[functions.storage-health]
verify_jwt = false
